=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/schema/1.0/policy-module.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:umc:authorization:policy-module:1.0",
  "title": "UMC Policy Module 1.0",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "$schema",
    "schemaVersion",
    "contextSchemaVersion",
    "namespace",
    "policyVersion",
    "moduleId",
    "statements"
  ],
  "properties": {
    "$schema": {
      "const": "urn:umc:authorization:policy-module:1.0"
    },
    "schemaVersion": {
      "const": "1.0"
    },
    "contextSchemaVersion": {
      "type": "string"
    },
    "namespace": {
      "type": "string"
    },
    "policyVersion": {
      "type": "string"
    },
    "moduleId": {
      "type": "string"
    },
    "statements": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  }
}

=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/authorization/challenger-role-resource.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "authorization-1.0",
  "namespace": "authorization",
  "policyVersion": "1.0.0",
  "moduleId": "challenger-role-resource",
  "statements": [
    {
      "id": "challenger-role.read.authenticated",
      "effect": "ALLOW",
      "actions": [
        "challenger-role:read"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "subject.authenticated"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "challenger-role.manage.active-central-core",
      "effect": "ALLOW",
      "actions": [
        "challenger-role:create",
        "challenger-role:delete"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.activeCentralCore"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    }
  ]
}

=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/project/matching-round.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "project-1.0",
  "namespace": "project",
  "policyVersion": "1.1.0",
  "moduleId": "matching-round",
  "statements": [
    {
      "id": "matching.list.member",
      "effect": "ALLOW",
      "actions": [
        "project-matching-round:list"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "matching.manage.super-admin",
      "effect": "ALLOW",
      "actions": [
        "project-matching-round:create",
        "project-matching-round:update",
        "project-matching-round:delete",
        "project-matching-round:human-auto-decide"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeSuperAdmin"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "matching.manage.central",
      "effect": "ALLOW",
      "actions": [
        "project-matching-round:create",
        "project-matching-round:update",
        "project-matching-round:delete",
        "project-matching-round:human-auto-decide"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeCentralCoreInResourceGisu"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "matching.manage.chapter",
      "effect": "ALLOW",
      "actions": [
        "project-matching-round:create",
        "project-matching-round:update",
        "project-matching-round:delete",
        "project-matching-round:human-auto-decide"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeChapterPresidentForResource"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "matching.auto-decide.scheduler",
      "effect": "ALLOW",
      "actions": [
        "project-matching-round:system-auto-decide"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "SYSTEM"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.systemId"
            },
            "right": {
              "type": "STRING",
              "value": "matching-round-scheduler"
            }
          }
        ]
      },
      "outcomes": []
    }
  ]
}

=== UMC-PRODUCT/cygnus-server/src/test/resources/policies/task-2/valid/demo.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "test-1.0",
  "namespace": "test",
  "policyVersion": "1.0.0",
  "moduleId": "demo",
  "statements": [
    {
      "id": "allow-active",
      "actions": [
        "project:read"
      ],
      "effect": "ALLOW",
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "subject.active"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    }
  ]
}

=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/project/statistics.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "project-1.0",
  "namespace": "project",
  "policyVersion": "1.1.0",
  "moduleId": "statistics",
  "statements": [
    {
      "id": "statistics.project.owner",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-project"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.isProductOwner"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.project.sub-pm",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-project"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.isActivePlanMember"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.project.super-admin",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-project"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeSuperAdmin"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.project.central",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-project"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeCentralCoreInResourceGisu"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.project.chapter",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-project"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeChapterPresidentForResource"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.project.school-core",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-project"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeSchoolCoreForResource"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.chapter.super-admin",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-chapter"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeSuperAdmin"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.chapter.central",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-chapter"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeCentralCoreInResourceGisu"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.chapter.chapter",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-chapter"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeChapterPresidentForResource"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.chapter.school-core",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-chapter"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.activeSchoolCoreForResource"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "statistics.public-matching.member",
      "effect": "ALLOW",
      "actions": [
        "project-statistics:read-public-matching"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "subject.kind"
            },
            "right": {
              "type": "ENUM",
              "value": "MEMBER"
            }
          }
        ]
      },
      "outcomes": []
    }
  ]
}

=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/certificate/certificate-resource.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "certificate-1.0",
  "namespace": "certificate",
  "policyVersion": "1.0.0",
  "moduleId": "certificate-resource",
  "statements": [
    {
      "id": "certificate.manage.super-admin",
      "effect": "ALLOW",
      "actions": [
        "certificate:issue-admin",
        "certificate:revoke"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.superAdmin"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "certificate.manage.active-central-core-in-target-gisu",
      "effect": "ALLOW",
      "actions": [
        "certificate:issue-admin",
        "certificate:revoke"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.activeCentralCoreInTargetGisu"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    }
  ]
}

=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/storage/storage-resource.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "storage-1.0",
  "namespace": "storage",
  "policyVersion": "1.0.0",
  "moduleId": "storage-resource",
  "statements": [
    {
      "id": "storage-file.delete.uploader",
      "effect": "ALLOW",
      "actions": [
        "storage-file:delete"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.isUploader"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "storage-file.delete.super-admin",
      "effect": "ALLOW",
      "actions": [
        "storage-file:delete"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.superAdmin"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    }
  ]
}

=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/chat/chat-resource.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "chat-1.0",
  "namespace": "chat",
  "policyVersion": "1.0.0",
  "moduleId": "chat-resource",
  "statements": [
    {
      "id": "chat.room-member",
      "effect": "ALLOW",
      "actions": [
        "chat-room:read",
        "chat-room-summary:read",
        "chat-message:create",
        "chat-message:read",
        "chat-reaction:update",
        "chat-read:update",
        "chat-read-status:read"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.isRoomMember"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "chat.message-author-update",
      "effect": "ALLOW",
      "actions": [
        "chat-message:update"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.isRoomMember"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          },
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.isMessageAuthor"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          }
        ]
      },
      "outcomes": []
    },
    {
      "id": "chat.message-author-or-moderator-delete",
      "effect": "ALLOW",
      "actions": [
        "chat-message:delete"
      ],
      "condition": {
        "type": "ALL",
        "conditions": [
          {
            "type": "PREDICATE",
            "operator": "EQ",
            "left": {
              "type": "ATTRIBUTE",
              "name": "relation.isRoomMember"
            },
            "right": {
              "type": "BOOLEAN",
              "value": true
            }
          },
          {
            "type": "ANY",
            "conditions": [
              {
                "type": "PREDICATE",
                "operator": "EQ",
                "left": {
                  "type": "ATTRIBUTE",
                  "name": "relation.isMessageAuthor"
                },
                "right": {
                  "type": "BOOLEAN",
                  "value": true
                }
              },
              {
                "type": "PREDICATE",
                "operator": "EQ",
                "left": {
                  "type": "ATTRIBUTE",
                  "name": "relation.isModerator"
                },
                "right": {
                  "type": "BOOLEAN",
                  "value": true
                }
              }
            ]
          }
        ]
      },
      "outcomes": []
    }
  ]
}

=== UMC-PRODUCT/cygnus-server/src/main/resources/policies/notice/notice-resource.policy.json
{
  "$schema": "urn:umc:authorization:policy-module:1.0",
  "schemaVersion": "1.0",
  "contextSchemaVersion": "notice-1.0",
  "namespace": "notice",
  "policyVersion": "1.0.0",
  "moduleId": "notice-resource",
  "statements": [
    {
      "id": "notice.read.active-central-core",
      "effect": "ALLOW",
      "actions": [
        "notice:read"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.activeCentralCore"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "notice.read.target-challenger",
      "effect": "ALLOW",
      "actions": [
        "notice:read"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.isTargetChallenger"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "notice.read.active-role-target",
      "effect": "ALLOW",
      "actions": [
        "notice:read"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.activeRoleCanReadTarget"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "notice.update-delete.author",
      "effect": "ALLOW",
      "actions": [
        "notice:update",
        "notice:delete"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.isNoticeAuthor"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "notice.update-delete.super-admin",
      "effect": "ALLOW",
      "actions": [
        "notice:update",
        "notice:delete"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.superAdmin"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "notice.recipients.active-manager",
      "effect": "ALLOW",
      "actions": [
        "notice:read-recipients",
        "notice:check-recipients"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.activeManagerForTarget"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    },
    {
      "id": "notice.create.active-target-creator",
      "effect": "ALLOW",
      "actions": [
        "notice:create"
      ],
      "condition": {
        "type": "PREDICATE",
        "operator": "EQ",
        "left": {
          "type": "ATTRIBUTE",
          "name": "relation.activeCreatorForTarget"
        },
        "right": {
          "type": "BOOLEAN",
          "value": true
        }
      },
      "outcomes": []
    }
  ]
}
